sort:
  - name: What_is_TEA?
    path: What_is_TEA?/README.md
    children:
      - name: Broken_internet_needs_a_fix.md
      - name: How_TEA_fix_internet.md
      - name: TEA_vs_IPFS.md
      - name: TEA_vs_blockchain.md
      - name: TEA_vs_Trusted_computing.md
      - name: TEA_vs_wasm.md
      - name: Key_concepts.md
      - name: Use_cases.md
      - name: New_business_models.md
  - name: Blog_and_Vlog
    path: Blog_and_Vlog/README.md
    children:
      - name: Gluon_yet_another_crypto_wallet.md
      - name: Can_trusted_computing_protect_your_digital_assets.md
      - name: Turn_ipfs_file_system_to_ipfs_function_service.md
      - name: Tea_at_the_Edge_taas_concept.md
      - name: TEA_Project_business_model.md
      - name: TEA_Project_Intro.md
  - name: Try_the_demo
    path: Try_the_demo/README.md
    children:
      - name: Easy_start.md
      - name: Advanced_demo.md
      - name: Deploy_data_run_adhoc_code.md
      - name: Deploy_code_run_adhoc_data.md
      - name: Run_your_own_TEA_node.md
  - name: Business_model
    path: Business_model/README.md
    children:
      - name: Double_loops.md
      - name: Life_cycle.md
      - name: Birth_control.md
      - name: Public_services.md
  - name: Under_the_hood
    path: Under_the_hood/README.md
    children:
      - name: Tea_on_layer1.md
      - name: Delegation_chain.md
      - name: Repin.md
      - name: Trust_chain.md
      - name: Easy_start.md
      - name: Use_your_own_picture.md
      - name: Deploy_your_own_code.md
      - name: Select_an_executor.md
      - name: Revenue_distribution.md
      - name: Submit_task.md
  - name: FAQ
    path: FAQ/README.md
    children:
      - name: why_not_secure.md
      - name: how_to_install_polkadot_extension.md  
      - name: how_to_create_a_new_account.md
      - name: how_to_get_free_test_token_to_start.md
  - name: 中文资料
    path: chn/README.md
    children:
      - name: chn_teaser
        path: /chn/chn_teaser.md
      - name: chn_token_economy
        path: /chn/chn_token_economy.md
      - name: chn_differences.md
        path: /chn/chn_differences

  # - name: 测试中文目录
  #   path: test_chinese/readme.md
  #   children:
  #     - name: 第一个中文文件
  #       path: /test_chinese/first.md


